package_rename_config:
  android:
    app_name: "ICT Students"
    package_name: "com.ictmu.ict_mu_students"
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "ICT Students"
    bundle_name: "com.ictmu.ictMuStudents"
    override_old_package: # (String) Use this to replace the old bundle identifier with the new bundle identifier
    package_name: # (String) The product bundle identifier of the ios app